# Spring properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/test
      
  #profiles: mysql

  #datasource:
   # driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost/usermanagement
    #username: root
    #password: password
      
  application:
    name: user-service  # Service registers under this name

endpoints:
  health:
    enabled: yes
  shutdown:
    enabled: yes

management:
    context-path: /admin
logging:
  level:
    org:
      springframework:
        web:
          client: DEBUG

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port
